[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "14.15.5"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
